title: Hello, world! I'm Ryan Stegmann
description: > # this means to ignore newlines until "baseurl:"
  My name is Ryan. I’m a JavaScript freelance developer,
  coffee drinker and huge nerd living in
  Riverside, California.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.rsteg.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Ryan Stegmann # add your name
author-img: ryan-stegmann.png # add your photo
about-author: I am a web developer focusing on front-end development. Always hungry to keep learning. # add description
social-twitter: rstegd # add your Twitter handle
social-facebook: rstegg # add your Facebook handle
social-github: rstegg # add your Github handle
social-linkedin: rsteg # add your Linkedin handle
social-email: stegmannrd@gmail.com # add your Email address

# Disqus
discus-identifier: rsteg # add your discus identifier

# Tracker
analytics: UA-96677476-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
